### ISSUE TITLE
Criar Figma da pagina Area Logada

### ISSUE THREAD

**Issue by jose-santos88** [jose-santos88/piFrontEnd#10]

**Comment by gxudre** [comment]
![Area Logada](https://user-images.githubusercontent.com/62075775/232921538-a86817b6-9694-429a-93ca-cdb65cb7a345.png)
![Area logada outro end](https://user-images.githubusercontent.com/62075775/232921552-f2b3a9a1-679c-4c58-810f-2fe30884c2bc.png)
